# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cbfa5ea70d5295b98cd60a727f4f13a78620f162d076a64d6d6aac04894b3314a544b3364acf9136db99c99a6e34ddfd7d9407786d1f25cc5e6a35ca3cecb6de

test:
  secret_key_base: f8b5f59a1bc6d4c8e690d5e39ff48cddd7755873ab40a56e3edecacc93b0016e4a679d12ac85e61ccd68e5afc5b25e3d2c494c25a03e73aeeb60bb37a30576de

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
